---
swagger: "2.0"
info:
  description: This is an example of using OAuth2 Application Flow in a specification to describe security to your API.
  version: 1.0.0
  title: Sample Application Flow OAuth2 Project
host: www.zhengxianqian.club
basePath: /
schemes:
- https
paths:
  /user/session:
    post:
      tags:
      - user
      summary: Users login
      description: Users login
      parameters:
        - name: body
          in: body
          required: true
          schema:
            $ref: '#/definitions/loginCode'
      responses:
        200:
          description: OK, return the user's info and hasAuthenticated.
          schema:
            $ref: '#/definitions/userInfo'
        400:
          description: Error
          schema:
            $ref: '#/definitions/ErrorResponse'
  /user/proof:
    get:
      tags:
      - user
      summary: get user's indentity info
      parameters:
      - name: userId
        in: query
        required: true
        type: string
      responses:
        200:
          description: OK, return the user indentity info
          schema:
            $ref: '#/definitions/idenInfoWithCredit'
        400:
          description: Error
          schema:
            $ref: '#/definitions/ErrorResponse'
    post:
      tags:
      - user
      summary: User provide his prove identity.
      parameters:
      - in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/idenInfo'
      responses:
        200:
          description: OK, set creditScore 100.
        400:
          description: Error
          schema:
            $ref: '#/definitions/ErrorResponse'
  /user/info:
    put:
      tags:
      - user
      summary: User modify his basic info.
      parameters:
      - name: body
        in: body
        required: true
        schema:
          $ref: '#/definitions/userInfo2'
      responses:
        200:
          description: modify success
          schema:
            $ref: '#/definitions/userInfo'
        400:
          description: Error
          schema:
            $ref: '#/definitions/ErrorResponse'
  /user/{userId}/proof/state:
    get:
      tags:
      - user
      summary: User get his authState.
      parameters:
      - name: userId
        in: path
        required: true
        type: string
      responses:
        200:
          description: check success
          schema:
            $ref: '#/definitions/proveState'
        400:
          description: Error
          schema:
            $ref: '#/definitions/ErrorResponse'
  /user/{userId}/balance:
    get:
      tags:
      - user
      summary: User get the balance.
      parameters:
      - name: userId
        in: path
        required: true
        type: string
      responses:
        200:
          description: publish success
          schema:
            properties:
              balance:
                type: number
        400:
          description: Error
          schema:
            $ref: '#/definitions/ErrorResponse'
    put:
      tags:
      - user
      summary: User recharge.
      parameters:
      - name: userId
        in: path
        required: true
        type: string
      - name: body
        in: body
        required: true
        schema:
          properties:
            money:
              type: string
      responses:
        200:
          description: publish success
          schema:
            properties:
              balance:
                type: number
        400:
          description: Error
          schema:
            $ref: '#/definitions/ErrorResponse'
  /group:
    get:
      tags:
      - group
      summary: User get the all group.
      responses:
        200:
          description: create success
          schema:
            type: array
            items:
              type: string
        400:
          description: Error
          schema:
            $ref: '#/definitions/ErrorResponse'
  /group/{userId}:
    post:
      tags:
      - group
      summary: User creates the group.
      parameters:
      - name: userId
        in: path
        required: true
        type: string
      - name: body
        in: body
        required: true
        schema:
          properties:
            groupName:
              type: string
      responses:
        200:
          description: create success
        400:
          description: Error
          schema:
            $ref: '#/definitions/ErrorResponse'
    put:
      tags:
      - group
      summary: User joins the task.
      parameters:
      - name: userId
        in: path
        required: true
        type: string
      responses:
        200:
          description: join success
        400:
          description: Error
          schema:
            $ref: '#/definitions/ErrorResponse'
    get:
      tags:
      - group
      summary: User get his join or created group.
      parameters:
      - name: userId
        in: path
        required: true
        type: string
      responses:
        200:
          description: get success
          schema:
            type: object
            properties:
              created:
                type: array
                items:
                  type: string
              joined:
                type: array
                items:
                  type: string
        400:
          description: Error
          schema:
            $ref: '#/definitions/ErrorResponse'
  /task:
    get:
      tags:
      - task
      summary: Returns all related tasks according to the pageId.
      description: Returns the published tasks, the max number is 10. If the page is the last page, the return all left.
      parameters:
      - name: pageId
        in: query
        description: Page number
        required: true
        type: integer
        default: 0
      responses:
        200:
          description: success
          schema:
            type: array
            items:
              $ref: '#/definitions/task'
        400:
          description: Error
          schema:
            $ref: '#/definitions/ErrorResponse'
  /task/{userId}/publishment:
    get:
      tags:
      - task
      summary: Returns all his own published tasks in the page.
      description: Returns the published tasks, the max number is 10. If the page is the last page, the return all left.
      parameters:
      - name: userId
        in: path
        required: true
        type: string
      responses:
        200:
          description: success
          schema:
            type: array
            items:
              $ref: '#/definitions/task'
        400:
          description: Error
          schema:
            $ref: '#/definitions/ErrorResponse'
  /task/{userId}/acceptment:
    get:
      tags:
      - task
      summary: Returns all his accepted tasks in the page.
      description: Returns the published tasks, the max number is 10. If the page is the last page, the return all left.
      parameters:
      - name: userId
        in: path
        required: true
        type: string
      responses:
        200:
          description: success
          schema:
            type: array
            items:
              $ref: '#/definitions/task'
        400:
          description: Error
          schema:
            $ref: '#/definitions/ErrorResponse'
  /task/{taskId}:
    get:
      tags:
      - task
      summary: Returns one task's detail
      description: Returns one task's detail
      parameters:
      - name: taskId
        in: path
        description: The task's id in database.
        required: true
        type: string
      responses:
        200:
          description: success
          schema:
            $ref: '#/definitions/allTaskDetail'
        400:
          description: Error
          schema:
            $ref: '#/definitions/ErrorResponse'
  /task/{taskId}/publisher:
    get:
      tags:
      - task
      summary: Publisher get the info of accepters
      parameters:
      - name: taskId
        in: path
        required: true
        type: string
      - name: userId
        in: query
        required: true
        type: string
      responses:
        200:
          description: receive success
          schema:
            type: array
            items:
              type: object
              properties:
                avartUrl: 
                  type: string
                nickName:
                  type: string
                tel:
                  type: string
        400:
          description: Error
          schema:
            $ref: '#/definitions/ErrorResponse'
    post:
      tags:
      - task
      summary: User publish the task.
      parameters:
      - name: taskId
        in: path
        required: true
        type: string
      - name: body
        in: body
        required: true
        schema:
          properties:
            userId:
              type: string
            content:
              $ref: '#/definitions/publisherInfo'
      responses:
        200:
          description: receive success
        400:
          description: Error
          schema:
            $ref: '#/definitions/ErrorResponse'
    put:
      tags:
      - task
      summary: Publisher add the task info.
      parameters:
      - name: taskId
        in: path
        required: true
        type: string
      - name: body
        in: body
        required: true
        schema:
          properties:
            userId:
              type: string
            info:
              type: string
      responses:
        200:
          description: receive success
        400:
          description: Error
          schema:
            $ref: '#/definitions/ErrorResponse'
    delete:
      tags:
      - task
      summary: Publisher abort the task.
      description: This operation shows how to override the global security defined above, as we want to open it up for all users.
      parameters:
      - name: taskId
        in: path
        required: true
        type: string
      - name: body
        in: body
        required: true
        schema:
          properties:
            userId: 
              type: string
      responses:
        200:
          description: abort success
        400:
          description: Error
          schema:
            $ref: '#/definitions/ErrorResponse'
  /task/{taskId}/accepter:
    post:
      tags:
      - task
      summary: User commit the job.
      description: This operation shows how to override the global security defined above, as we want to open it up for all users.
      parameters:
      - name: taskId
        in: path
        required: true
        type: string
      - name: body
        in: body
        required: true
        schema:
          properties:
            userId:
              type: string
            cert:
              $ref: '#/definitions/cert'
      responses:
        200:
          description: complete success
        400:
          description: Error
          schema:
            $ref: '#/definitions/ErrorResponse'
    delete:
      tags:
      - task
      summary: Accepter abandon the task.
      description: This operation shows how to override the global security defined above, as we want to open it up for all users.
      parameters:
      - name: taskId
        in: path
        required: true
        type: string
      - name: body
        in: body
        required: true
        schema:
          properties:
            userId: 
              type: string
      responses:
        200:
          description: abandon success
        400:
          description: Error
          schema:
            $ref: '#/definitions/ErrorResponse'
  /image:
    post:
      tags:
      - 'System'
      summary: 'upload image'
      consumes:
      - 'multipart/form-data'
      parameters:
      - in: 'formData'
        name: 'image'
        type: 'file'
        description: 'image'
        required: true
      responses:
        200:
          description: 'OK'
          schema:
            type: 'object'
            properties:
              url:
                type: 'string'
        400:
          description: 'Error'
          schema:
            $ref: '#/definitions/ErrorResponse'
definitions:
  ErrorResponse:
    type: object
    properties:
      message:
        type: string
  loginCode:
    properties:
      js_code:
        description: user's js_code
        type: string
      app_id:
        description: miniprogram app_id
        type: string
      app_secret:
        description: miniprogram app_secret
        type: string
      encryptedData:
        description: user's encryptedData when he/she has authensized getUserInfo
        type: string
  userInfo2:
    properties:
      nickName:
        type: string
      avartUrl:
        type: string
  userInfo:
    properties:
      userId:
        type: string
      nickName:
        type: string
      avartUrl:
        type: string
      proveState:
        type: string
  idenInfo:
    properties:
      name:
        type: string
      sex:
        type: string
      idenType:
        type: string
      tel:
        type: string
      school:
        type: string
      company:
        type: string
      id:
        type: string
        description: student id or worker id
      cert:
        description: user's cert path
        type: string
  task:
    properties:
      id:
        type: string
      icon:
        type: string
        description: the issuer's head pic
      title:
        type: string
      desc:
        type: string
      money:
        type: number
      left:
        type: integer
        description: the num of the left task.
  taskdetail:
    properties:
      type:
        type: string
      wjxId:
        type: string
        description: if the type is '问卷星', return wjxId.
      title:
        type: string
      desc:
        type: string
      money:
        type: number
      num:
        type: integer
        description: the num of people who have got money.
      left:
        type: integer
        description: the num of the left task.
      condition:
        $ref: '#/definitions/condition'
  publisherInfo:
    properties:
      avartUrl:
        type: string
      nickName:
        type: string
      tel:
        type: string
  cert:
    type: object
    properties:
      files:
        type: array
        items:
          type: string
      remarks:
        type: string
  condition:
    properties:
      groups:
        type: array
        items:
          type: string
      sex:
        type: string
      creditScore:
        type: integer
  idenInfoWithCredit:
    properties:
      idenInfo:
        $ref: '#/definitions/idenInfo'
      creditScore:
        type: integer
  proveState:
    properties:
      proveState:
        type: string
  allTaskDetail:
    properties:
      user:
        $ref: '#/definitions/publisherInfo'
      content:
        $ref: '#/definitions/taskdetail'
      isPublisher:
        type: boolean
      hasReceived:
        type: integer
        description: 0 stands for hasn't, 1 stands for has received, 2 stands for under review, 3 stands for has completed